---
- name: Install k3s master
  shell: curl -sfL https://get.k3s.io | INSTALL_K3S_EXEC="--write-kubeconfig-mode 644" sh -
  args:
    creates: /usr/local/bin/k3s
  become: true

- name: Copy kubeconfig to control node
  fetch:
    src: /etc/rancher/k3s/k3s.yaml
    dest: "{{ playbook_dir }}/../kubeconfig"
    flat: yes
  become: true
